
import { VideoProject } from "@/types/videos";

// Keep ONLY your current local demo videos.
// Add more mp4s from `public/project-videos/` by creating new items below.
export const allVideoProjects: VideoProject[] = [
  {
    id: "LongVideo01",
    video_title: "Story Tempo Drive 🧠",
    video_description: "Marathi: दीर्घ व्हिडिओमध्ये स्टोरीचा Flow / English: Long-form with clean narrative flow 🧠",

    tags: ["Long Videos"],
    cover_image: "/project-images/Long-Videos-tham.png",
    publish_date: "2025-07-01",
    client_name: "Self",
    client_image: "/project-images/Long-Videos-tham.png",
    client_feedback: "",
    video_link:
      "https://res.cloudinary.com/e7pvfh5k/video/upload/v1783483595/Long_Video_01_upcrb8.mp4",
    video_path: undefined,

    project_images: [],
    category: ["Long Videos"],
    duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "LongVideo02",
    video_title: "Edit Rhythm Mastery 🎬",
    video_description: "Marathi: एडिटिंगमध्ये परफेक्ट Rhythm / English: Clean edit rhythm for watchable flow 🎬",

    tags: ["Long Videos"],
    cover_image: "/project-images/Long-Videos-tham.png",
    publish_date: "2025-07-02",
    client_name: "Self",
    client_image: "/project-images/Long-Videos-tham.png",
    client_feedback: "",
    video_link:
      "https://res.cloudinary.com/e7pvfh5k/video/upload/v1783483604/Long_Video_02_1_oqvzzo.mp4",
    video_path: undefined,

    project_images: [],
    category: ["Long Videos"],
    duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },
  
  // {
  //   id: "LongVideo03",
  //   video_title: "Cinematic Story Arc ✨",
  //   video_description: "Marathi: Cinematic story arc / English: Strong narrative arc with cinematic pacing ✨",
  //   tags: ["Long Videos"],
  //   cover_image: "/project-images/Long-Videos-tham.png",
  //   publish_date: "2025-07-03",
  //   client_name: "Self",
  //   client_image: "/project-images/Long-Videos-tham.png",
  //   client_feedback: "",
  //   video_link: "",
  //   video_path: undefined,

  //   project_images: [],
  //   category: ["Long Videos"],
  //   duration: "4:26",
  //   software_used: ["Adobe Premiere Pro"],
  // },

 //Graphics Designs

  {
    id: "ShortFormContent01",
    video_title: "AI Visual Story  🤖",

    video_description: "I create high-performing short-form content optimized for platforms like YouTube Shorts, Instagram Reels, and TikTok. By combining fast-paced editing, motion graphics, and trend-driven storytelling, I help brands and creators increase engagement and reach.",
    tags: ["Short Form Content"],
    cover_image: "/project-images/short-form-content.png",
    publish_date: "2025-07-03",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://res.cloudinary.com/e7pvfh5k/video/upload/v1783425451/Short_Form_Video_01_vqpsie.mp4",
    video_path: undefined,

    project_images: [],
    category: ["Short Form Content"],
    duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },

  {
    id: "ShortFormContent02",
    video_title: "Short Form Spark  ⚡",
    video_description: "I create high-performing short-form content optimized for platforms like YouTube Shorts, Instagram Reels, and TikTok. By combining fast-paced editing, motion graphics, and trend-driven storytelling, I help brands and creators increase engagement and reach.",
    tags: ["Short Form Content"],
    cover_image: "/project-images/short-form-content.png",
    publish_date: "2025-07-04",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://res.cloudinary.com/e7pvfh5k/video/upload/v1783425101/Short_Form_Video_04_n2b5oq.mp4",
    video_path: undefined,

    project_images: [],
    category: ["Short Form Content"],
    duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "ShortFormContent03",
    video_title: "Viral Cut Catalyst  🔥",
    video_description: "I create high-performing short-form content optimized for platforms like YouTube Shorts, Instagram Reels, and TikTok. By combining fast-paced editing, motion graphics, and trend-driven storytelling, I help brands and creators increase engagement and reach.",
    tags: ["Short Form Content"],
    cover_image: "/project-images/short-form-content.png",
    publish_date: "2025-07-05",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://res.cloudinary.com/e7pvfh5k/video/upload/v1783425095/Short_Form_Video_02_qpgg9g.mp4",
    video_path: undefined,

    project_images: [],
    category: ["Short Form Content"],
    duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "ShortFormContent04",
    video_title: "Hook & Hold Loop  👀",
    video_description: "I create high-performing short-form content optimized for platforms like YouTube Shorts, Instagram Reels, and TikTok. By combining fast-paced editing, motion graphics, and trend-driven storytelling, I help brands and creators increase engagement and reach.",
    tags: ["Short Form Content"],
    cover_image: "/project-images/short-form-content.png",
    publish_date: "2025-07-06",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://res.cloudinary.com/e7pvfh5k/video/upload/v1783425087/Short_Form_Video_07_vrmpvd.mp4",
    video_path: undefined,

    project_images: [],
    category: ["Short Form Content"],
    duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "ShortFormContent05",
    video_title: "Motion Beat Spark  ⚡",
    video_description: "I create high-performing short-form content optimized for platforms like YouTube Shorts, Instagram Reels, and TikTok. By combining fast-paced editing, motion graphics, and trend-driven storytelling, I help brands and creators increase engagement and reach.",
    tags: ["Short Form Content"],
    cover_image: "/project-images/short-form-content.png",
    publish_date: "2025-07-07",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://res.cloudinary.com/e7pvfh5k/video/upload/v1783425087/Short_Form_Video_06_jttcvb.mp4",
    video_path: undefined,

    project_images: [],
    category: ["Short Form Content"],
    duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "ShortFormContent06",
    video_title: "Quick Story Punch  ✨",
    video_description: "I create high-performing short-form content optimized for platforms like YouTube Shorts, Instagram Reels, and TikTok. By combining fast-paced editing, motion graphics, and trend-driven storytelling, I help brands and creators increase engagement and reach.",
    tags: ["Short Form Content"],
    cover_image: "/project-images/short-form-content.png",
    publish_date: "2025-07-08",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://res.cloudinary.com/e7pvfh5k/video/upload/v1783425069/Short_Form_Video_05_sc231l.mp4",
    video_path: undefined,
    project_images: [],

    category: ["Short Form Content"],
    duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "ShortFormContent07",
    video_title: "Retention Remix  🎬",
    video_description: "I create high-performing short-form content optimized for platforms like YouTube Shorts, Instagram Reels, and TikTok. By combining fast-paced editing, motion graphics, and trend-driven storytelling, I help brands and creators increase engagement and reach.",
    tags: ["Short Form Content"],
    cover_image: "/project-images/short-form-content.png",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://res.cloudinary.com/e7pvfh5k/video/upload/v1783425069/Short_Form_Video_03_e689me.mp4",
    video_path: undefined,

    project_images: [],
    category: ["Short Form Content"],
    duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },


  // AI CONTENTS

  {
    id: "AIContent01",

    video_title: "Neon Narrative: AI Short Cut  🚀",

    video_description: "I create AI-powered short videos that combine storytelling, advanced AI tools, and cinematic editing to produce engaging and visually stunning content. From concept development to final delivery, every project is designed to capture attention and maximize audience retention.",
    tags: ["AI Content"],
    cover_image: "/project-images/Ai-thamnail.png",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link:
      "https://res.cloudinary.com/e7pvfh5k/video/upload/v1783483607/AI_content1_vmpzej.mp4",
    video_path: undefined,

    project_images: [],
    category: ["Ai Videos"],
    duration: "6:32",
    software_used: ["Adobe Premiere Pro", "Google Flow", "ChatGPT"],
  },
  {
    id: "AIContent02",
    video_title: "Spark Slice: AI Short ⚡ ",

    video_description: "I create AI-powered short videos that combine storytelling, advanced AI tools, and cinematic editing to produce engaging and visually stunning content. From concept development to final delivery, every project is designed to capture attention and maximize audience retention.",
    tags: ["AI Content"],
    cover_image: "/project-images/Ai-thamnail.png",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link:
      "https://res.cloudinary.com/e7pvfh5k/video/upload/v1783483185/AI_content2_j6ctsn.mp4",
    video_path: undefined,

    project_images: [],
    category: ["Ai Videos"],
    duration: "6:32",
    software_used: ["Adobe Premiere Pro", "Google Flow", "ChatGPT"],
  },

  {
    id: "AIContent03",
    video_title: "Dreamflow Cut  ✨",

    video_description: "I create AI-powered short videos that combine storytelling, advanced AI tools, and cinematic editing to produce engaging and visually stunning content. From concept development to final delivery, every project is designed to capture attention and maximize audience retention.",
    tags: ["Ai Content"],
    cover_image: "/project-images/Ai-thamnail.png",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link:
      "https://res.cloudinary.com/e7pvfh5k/video/upload/v1783483118/AI_content3_jtug4y.mp4",
    video_path: undefined,

    project_images: [],
    category: ["Ai Videos"],
    duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },

  {
    id: "AIContent04",
    video_title: "Midnight Montage  🌙",
    video_description: "I create AI-powered short videos that combine storytelling, advanced AI tools, and cinematic editing to produce engaging and visually stunning content. From concept development to final delivery, every project is designed to capture attention and maximize audience retention.",
    tags: ["AI Content"],
    cover_image: "/project-images/Ai-thamnail.png",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link:
      "https://res.cloudinary.com/e7pvfh5k/video/upload/v1783483179/AI_content4_tgsai1.mp4",
    video_path: undefined,

    project_images: [],
    category: ["Ai Videos"],
    duration: "6:32",
    software_used: ["Adobe Premiere Pro", "Google Flow", "ChatGPT"],
  },

  {
    id: "AIContent05",
    video_title: "Cinematic Pulse  🎬",

    video_description
    tags: ["AI Content"],
    cover_image: "/project-images/Ai-thamnail.png",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link:
      "https://res.cloudinary.com/e7pvfh5k/video/upload/v1783483124/AI_content5_gxy5wh.mp4",
    video_path: undefined,

    project_images: [],
    category: ["Ai Videos"],
    duration: "6:32",
    software_used: ["Adobe Premiere Pro", "Google Flow", "ChatGPT"],
  },

  {
    id: "AIContent06"
    video_title: "Flash Frame  ⚡",
    video_description: "I create AI-powered short videos that combine storytelling, advanced AI tools, and cinematic editing to produce engaging and visually stunning content. From concept development to final delivery, every project is designed to capture attention and maximize audience retention.",
    tags: ["AI Content"],
    cover_image: "/project-images/Ai-thamnail.png",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link:
      "https://res.cloudinary.com/e7pvfh5k/video/upload/v1783483809/AI_content6_nhpqby.mp4",
    video_path: undefined,

    project_images: [],
    category: ["Ai Videos"],
    duration: "6:32",
    software_used: ["Adobe Premiere Pro", "Google Flow", "ChatGPT"],
  },

  {
    id: "AIContent07"
    video_title: "Vivid Voiceover  🗣️",
    video_description: "I create AI-powered short videos that combine storytelling, advanced AI tools, and cinematic editing to produce engaging and visually stunning content. From concept development to final delivery, every project is designed to capture attention and maximize audience retention.",
    tags: ["AI Content"],
    cover_image: "/project-images/Ai-thamnail.png",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link:
      "https://res.cloudinary.com/e7pvfh5k/video/upload/v1783483570/AI_content7_h9xtdr.mp4",
    video_path: undefined,

    project_images: [],
    category: ["Ai Videos"],
    duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },

  {
    id: "GraphicsDesign01",
    video_title: "Poster Pop Mastery 🎨",
    video_description: "Bold layout, crisp typography, instant attention 🎨",
    tags: ["Graphics Design"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    // video_path: "/project-videos/AI_content7.mp4",
    project_images: ["/project-images/graphics-desing1.png"],
    category: ["Graphics Designs"],
    // duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },

    {
    id: "GraphicsDesign02",
    video_title: "Brand Heat Layout 🔥",
    video_description: "Design system feel with strong hierarchy and contrast 🔥",
    tags: ["Graphics Design"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    // video_path: "/project-videos/AI_content7.mp4",
    project_images: ["/project-images/graphics-desing2.png"],
    category: ["Graphics Designs"],
    // duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },


    {
    id: "graphicsDesign03",
    video_title: "Clean Grid Precision ✅",
    video_description: "Balanced spacing and sharp composition for modern visuals ✅",
    tags: ["Graphics Design"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    // video_path: "/project-videos/AI_content7.mp4",
    project_images: ["/project-images/graphics-desing3.png"],
    category: ["Graphics Designs"],
    // duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },

    {
    id: "GraphicsDesign04",
    video_title: "Color Impact Study 🌈",
    video_description: "Vibrant palette work that pops on every screen 🌈",
    tags: ["Graphics Design"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    // video_path: "/project-videos/AI_content7.mp4",
    project_images: ["/project-images/graphics-desing4.png"],
    category: ["Graphics Designs"],
    // duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },
    {
    id: "GraphicsDesign05",
    video_title: "Typography Weapon ⚡",
    video_description: "Type-driven design with confident weight and rhythm ⚡",
    tags: ["Graphics Design"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    // video_path: "/project-videos/AI_content7.mp4",
    project_images: ["/project-images/graphics-desing5.png"],
    category: ["Graphics Designs"],
    // duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "GraphicsDesign06",
    video_title: "Visual Flow Composition 🧩",
    video_description: "Tuned alignment and motion-like visual direction 🧩",
    tags: ["Graphics Design"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    // video_path: "/project-videos/AI_content7.mp4",
    project_images: ["/project-images/graphics-desing6.png"],
    category: ["Graphics Designs"],
    // duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },

    {
    id: "GraphicsDesign07",
    video_title: "Detail-First Layout 🔍",
    video_description: "Micro-spacing and clean edges that feel premium 🔍",
    tags: ["Graphics Design"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    // video_path: "/project-videos/AI_content7.mp4",
    project_images: ["/project-images/graphics-desing7.png"],
    category: ["Graphics Designs"],
    // duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },


    {
    id: "graphicsDesign08",
    video_title: "Modern Minimal Splash ✨",
    video_description: "Simplified elements, bold focal point, clean finish ✨",
    tags: ["Graphics Design"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    // video_path: "/project-videos/AI_content7.mp4",
    project_images: ["/project-images/graphics-desing8.png"],
    category: ["Graphics Designs"],
    // duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },

    {
    id: "GraphicsDesign09",
    video_title: "Contrast & Clarity 🎯",
    video_description: "High-contrast structure for fast, clear reading 🎯",
    tags: ["Graphics Design"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    // video_path: "/project-videos/AI_content7.mp4",
    project_images: ["/project-images/graphics-desing9.png"],
    category: ["Graphics Designs"],
    // duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },
    {
    id: "GraphicsDesign10",
    video_title: "Creative Collage Energy 🌀",
    video_description: "Layered visuals with smooth balance and punch 🌀",
    tags: ["Graphics Design"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    // video_path: "/project-videos/AI_content7.mp4",
    project_images: ["/project-images/graphics-desing10.png"],
    category: ["Graphics Designs"],
    // duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "GraphicsDesign11",
    video_title: "Iconic Brand Moment 🏷️",
    video_description: "Instant recognition with clean brand-focused styling 🏷️",
    tags: ["Graphics Design"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    // video_path: "/project-videos/AI_content7.mp4",
    project_images: ["/project-images/graphics-desing11.png"],
    category: ["Graphics Designs"],
    // duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "GraphicsDesign12",
    video_title: "Layout Rhythm & Balance ⚖️",
    video_description: "Careful grid spacing for a smooth, premium feel ⚖️",
    tags: ["Graphics Design"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    // video_path: "/project-videos/AI_content7.mp4",
    project_images: ["/project-images/graphics-desing12.png"],
    category: ["Graphics Designs"],
    // duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "GraphicsDesign13",
    video_title: "Hero Banner Punch 🧨",
    video_description: "Strong centerpiece with sharp supporting details 🧨",
    tags: ["Graphics Design"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    // video_path: "/project-videos/AI_content7.mp4",
    project_images: ["/project-images/graphics-desing13.png"],
    category: ["Graphics Designs"],
    // duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "GraphicsDesign14",
    video_title: "Smooth Minimal Poster 📐",
    video_description: "Clean geometry and refined finishing touches 📐",
    tags: ["Graphics Design"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    // video_path: "/project-videos/AI_content7.mp4",
    project_images: ["/project-images/graphics-desing14.png"],
    category: ["Graphics Designs"],
    // duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "GraphicsDesign15",
    video_title: "Premium Visual Storytelling 📚",
    video_description: "Designed for impact—clarity, emotion, and style 📚",
    tags: ["Graphics Design"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    // video_path: "/project-videos/AI_content7.mp4",
    project_images: ["/project-images/graphics-desing15.png"],
    category: ["Graphics Designs"],
    // duration: "6:32",
    software_used: ["Adobe Premiere Pro"],
  },

  //youtube videos thumbnails


  {
    id: "YouTubeThumbnail01",
    video_title: "Click Magnet Frame 👀",
    video_description: "Thumbnails built to stop the scroll—bold, readable, punchy 👀",

    tags: ["YouTube Thumbnails"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    project_images: ["/project-images/Thumbnail 01.png"],
    category: ["YouTube Videos Thumbnails"],
    software_used: ["Adobe Photoshop"],
  },
  {
    id: "YouTubeThumbnail02",
    video_title: "Contrast Punch Poster 🔥",
    video_description: "High-impact contrast and fast readability 🔥",
    tags: ["YouTube Thumbnails"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    project_images: ["/project-images/Thumbnail 02.png"],
    category: ["YouTube Thumbnails"],
    software_used: ["Adobe Photoshop"],
  },
  {
    id: "YouTubeThumbnail03",
    video_title: "Big Idea Tease 💡",
    video_description: "Story-driven text + bold focus 💡",
    tags: ["YouTube Thumbnails"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    project_images: ["/project-images/Thumbnail 03.png"],
    category: ["YouTube Thumbnails"],
    software_used: ["Adobe Photoshop"],
  },
  {
    id: "YouTubeThumbnail04",
    video_title: "Glow Hook Thumbnail ✨",
    video_description: "Shiny highlights + sharp headline ✨",
    tags: ["YouTube Thumbnails"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    project_images: ["/project-images/Thumbnail 04.png"],
    category: ["YouTube Thumbnails"],
    software_used: ["Adobe Photoshop"],
  },
  {
    id: "YouTubeThumbnail05",
    video_title: "Bold Truth Pop 🧨",
    video_description: "Punchy contrast designed for clicks 🧨",
    tags: ["YouTube Thumbnails"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    project_images: ["/project-images/Thumbnail 05.png"],
    category: ["YouTube Thumbnails"],
    software_used: ["Adobe Photoshop"],
  },
  {
    id: "YouTubeThumbnail06",
    video_title: "Clarity Commander 🎯",
    video_description: "Clean layout that reads instantly 🎯",
    tags: ["YouTube Thumbnails"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    project_images: ["/project-images/Thumbnail 06.png"],
    category: ["YouTube Thumbnails"],
    software_used: ["Adobe Photoshop"],
  },
  {
    id: "YouTubeThumbnail07",
    video_title: "Text-Heavy Impact ⚡",
    video_description: "High legibility with energetic spacing ⚡",
    tags: ["YouTube Thumbnails"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    project_images: ["/project-images/Thumbnail 07.png"],
    category: ["YouTube Thumbnails"],
    software_used: ["Adobe Photoshop"],
  },
  {
    id: "YouTubeThumbnail08",
    video_title: "Hook That Holds 👊",
    video_description: "A punchy headline with clean focus 👊",
    tags: ["YouTube Thumbnails"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    project_images: ["/project-images/Thumbnail 08.png"],
    category: ["YouTube Thumbnails"],
    software_used: ["Adobe Photoshop"],
  },
  {
    id: "YouTubeThumbnail09",
    video_title: "Bold Contrast Pop 🎬",
    video_description: "Designed for instant recognition 🎬",
    tags: ["YouTube Thumbnails"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    project_images: ["/project-images/Thumbnail 09.png"],
    category: ["YouTube Thumbnails"],
    software_used: ["Adobe Photoshop"],
  },
  {
    id: "YouTubeThumbnail10",
    video_title: "Click-Ready Final Frame 📌",
    video_description: "Crisp details and strong visual hierarchy 📌",

    tags: ["YouTube Thumbnails"],
    cover_image: "",
    publish_date: "2025-07-09",
    client_name: "Self",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    project_images: ["/project-images/Thumbnail 10.png"],
    category: ["YouTube Thumbnails"],
    software_used: ["Adobe Photoshop"],
  },
];


