import {
  Html,
  Head,
  Body,
  Container,
  Text,
  Section,
  Hr,

} from "@react-email/components";


type EmailTemplateProps = {
  name: string;
  email: string;
  projectType?: string;
  timeline?: string;
  message: string;
  time?: string;
  yourName?: string;
};

export const EmailTemplate = ({
  name,
  email,
  projectType = "Not specified",
  timeline = "Not specified",
  message,
  time,
  yourName = "sarang-bhavar",
}: EmailTemplateProps) => (
  <Html>
    <Head />
    <Body style={body}>
      <Container style={container}>
        {/* Header */}
        <Section style={header}>
          <Text style={brand}>
            <span style={emoji}>📩</span> New Contact Form Submission
          </Text>
        </Section>

        <Hr style={divider} />

        {/* Greeting */}
        <Section style={section}>
          <Text style={greetingText}>
            Hello <strong style={highlight}>{yourName}</strong>,
          </Text>
          <Text style={text}>
            You’ve received a new inquiry from your portfolio contact form.
          </Text>
        </Section>

        {/* Details (standard + clean) */}
        <Section style={detailsSection}>
          <Text style={tableTitle}>Contact Details</Text>

          <Text style={tableRow}>
            <strong style={th}>Name</strong>
            <Text style={tdInline}>{name}</Text>
          </Text>

          <Text style={tableRow}>
            <strong style={th}>Email</strong>
            <Text style={tdInline}>
              <a href={`mailto:${email}`} style={link}>
                {email}
              </a>
            </Text>
          </Text>

          <Text style={tableRow}>
            <strong style={th}>Project Type</strong>
            <Text style={tdInline}>{projectType}</Text>
          </Text>

          <Text style={tableRow}>
            <strong style={th}>Timeline</strong>
            <Text style={tdInline}>{timeline}</Text>
          </Text>

          <Text style={tableRow}>
            <strong style={th}>Project Details</strong>
          </Text>
          <Text style={messageBlock}>{message}</Text>

          <Text style={tableRow}>
            <strong style={th}>Submission Time</strong>
            <Text style={tdInline}>{time || "Not provided"}</Text>
          </Text>
        </Section>

        <Hr style={divider} />


        <Section style={footer}>
          <Text style={footerText}>
            This email was automatically generated by your portfolio contact
            system.
          </Text>
          <Text style={footerLink}>
            <a href=" " style={footerLinkStyle}>
              Visit Your Portfolio
            </a>
          </Text>
        </Section>
      </Container>
    </Body>
  </Html>
);


// Styles
const body = {
  backgroundColor: "#f7f9fc",
  fontFamily: "'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
  padding: "20px 0",
  lineHeight: "1.6",
  color: "#333",
};

const container = {
  backgroundColor: "#ffffff",
  borderRadius: "12px",
  padding: "30px 25px",
  maxWidth: "600px",
  margin: "0 auto",
  boxShadow: "0 6px 20px rgba(0,0,0,0.08)",
  border: "1px solid #e0e6ed",
};

const header = {
  textAlign: "center" as const,
  marginBottom: "15px",
};

const brand = {
  fontSize: "22px",
  fontWeight: "bold",
  color: "#2c3e50",
};

const emoji = {
  fontSize: "24px",
  marginRight: "8px",
};

const section = {
  marginBottom: "24px",
};

const detailsSection = {
  backgroundColor: "#f7fafc",
  padding: "15px 20px",
  borderRadius: "8px",
  border: "1px solid #e2e8f0",
};

const text = {
  fontSize: "16px",
  lineHeight: "1.6",
  color: "#34495e",
  marginBottom: "10px",
};

const greetingText = {
  ...text,
  fontSize: "18px",
  fontWeight: "600",
};

const highlight = {
  color: "#2980b9",
  fontWeight: "bold" as const,
};

const detailItem = {
  fontSize: "16px",
  marginBottom: "5px",
};

const detailValue = {
  fontWeight: "normal" as const,
};

const tableTitle = {
  fontSize: "16px",
  fontWeight: 700,
  color: "#2c3e50",
  marginBottom: "10px",
};

const tableRow = {
  fontSize: "15px",
  lineHeight: "1.6",
  color: "#34495e",
  marginBottom: "8px",
};

const th = {
  fontWeight: 700 as const,
  color: "#2c3e50",
};

const td = {
  fontWeight: "normal" as const,
  color: "#34495e",
};

const tdInline = {
  fontWeight: "normal" as const,
  color: "#34495e",
  display: "inline",
};


const messageBlock = {
  backgroundColor: "#ecf0f1",
  padding: "16px",
  borderRadius: "8px",
  fontSize: "15px",
  whiteSpace: "pre-line" as const,
  borderLeft: "4px solid #3498db",
  fontFamily: "monospace, sans-serif",
};

const link = {
  color: "#3498db",
  textDecoration: "none",
  fontWeight: "600" as const,
};


const divider = {
  borderColor: "#dfe4ed",
  margin: "25px 0",
};

const footer = {
  textAlign: "center" as const,
  marginTop: "20px",
};

const footerText = {
  fontSize: "13px",
  color: "#7f8c8d",
  marginBottom: "8px",
};

const footerLink = {
  marginTop: "5px",
};

const footerLinkStyle = {
  fontSize: "14px",
  color: "#3498db",
  textDecoration: "none",
  fontWeight: "500" as const,
};
